version: '3.8'

services:
  app:
    build: .
    command: ["/app/entrypoint.sh", "app"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env.development

  test:
    build: .
    command: ["/app/entrypoint.sh", "test"]
    environment:
      - ENVIRONMENT=test
    volumes:
      - .:/app
    profiles:
      - test