name: CI/CD Pipeline - statistics-service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy environment variables
        run: cp .env.example .env.development

      - name: Start Docker services
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          
          AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
          COURSES_SERVICE_URL: ${{ secrets.COURSES_SERVICE_URL }}
          
          SERVICE_USERNAME: ${{ secrets.SERVICE_USERNAME }}
          SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}

        run: |
          docker-compose --profile app up -d
          docker-compose logs -f &

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/health; then
              echo "API is ready"
              exit 0
            fi
            echo "Waiting for API... Attempt $i/30"
            docker-compose logs
            sleep 5
          done
          echo "API failed to start"
          docker-compose ps
          docker-compose logs --tail=100
          exit 1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          ENVIRONMENT: test
          HOST: 0.0.0.0
          PORT: 8080

          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?sslmode=require
          
          AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
          COURSES_SERVICE_URL: ${{ secrets.COURSES_SERVICE_URL }}
          
          SERVICE_USERNAME: ${{ secrets.SERVICE_USERNAME }}
          SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
        run: |
          PYTHONPATH=. pytest --cov=app --cov=tests --cov-report=term-missing --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Stop Docker services
        run: docker-compose down

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

      - name: Checkout GitHub Pages
        uses: actions/checkout@v4
        with:
          repository: memo2-2025-1c-group9/memo2-2025-1c-group9.github.io
          token: ${{ secrets.GH_PAT }}
          path: pages

      - name: Update coverage report
        run: |
          mkdir -p pages/coverages/statistics-service
          cp -r htmlcov/* pages/coverages/statistics-service/

      - name: Commit and push changes
        working-directory: pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update coverage report for statistics-service service"
          git push